name: Verify

on:
  issue_comment:
    types: [edited]

jobs:
  verify:
    runs-on: [ubuntu-latest]

    steps:
    - name: Check if all checkboxes are checked
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const checkboxPattern = /- \[ \]/g;
          const allChecked = comments.some(comment => !checkboxPattern.test(comment.body));

          if (!allChecked) {
            core.setFailed('Not all checkboxes have been checked.');
          }
